/**
 * Autoreq - Generate a single .js file requiring all files that matches a given file name
 * Copyright Rafael Salguero Iturrios 
 */

import fs = require("fs");
import path= require("path");

/**A file or folder path */
interface Path{
    /**File or folder full name */
    path: string;
    
    /**True if this is a file, false for a directory */
    isFile : boolean;
}

 
/**
 * Get all files that have the given file name recursively
 * @folder base folder
 * @fileName the name of the file including extension
 */
function getAllFiles(folder : string, fileName : string ) : string[] {
    var ret: string[] = [];
    
    var topFiles = (folder : string) : Path[] => 
    {
        return  fs
        .readdirSync(folder)
        .map(x => path.join(folder, x))
        .map(x=> 
        <Path>
        ({
            path :  x,
            isFile : fs.statSync(x).isFile()
        }));
    }
    
    var getFilesRec = (dir: string) =>
    {
        topFiles(dir).forEach(x=> 
        {
            if (!x.isFile)
                 getFilesRec(x.path);
            else if (path.basename(x.path)== fileName)
                ret.push( x.path);
                 
        })
    } 
    getFilesRec(folder);
    
    return ret;   
}

var args = process.argv.slice(2);
if (args.length  < 2)
{
    //Show console help:
    console.log("Generate a single .js file requiring all files that matches the given file name");
    console.log();
    console.log("Syntax: node autoreq.js fileName basePath output input1 [input2] [input3] ...  ")
    
    console.log ();
    console.log ("Arguments:");
    console.log ("- fileName : The file name to match including extension");
    console.log ("- output   : Path of the resulting generated file");
    console.log ("- input[N] : Path of input folders to scan");
    
    console.log ();
    console.log ("Example:");
    console.log ('node autoreq.js "main.js" "test\\result\\autoreq.js" "."');
}
else 
{
    var fileName = args[0];
    var output = args[1];
    var inputs = args.slice(2);
        
    //Get all files that matches the file name
    var files : string[] = [];
    inputs.map(x=> getAllFiles(x, fileName)).forEach( x=> files.push(...x));

    var data  = "//This file is autogenerated and should not be manually edited\n";

    files.forEach(x=> data += "require('" + x + "');\n");
    console.log(data);
    fs.writeFileSync(output,  data);
}


